Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVA, pull requests merged in 2023-09, with the labels that each got.

#592 fecha de adminision a la institucion
  app/Employee.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
  database/migrations/2023_09_01_100431_add_addmission_date_Employees_table.php
Labels: change

#595 Días asignados y saldo de vacaciones vigentes en reporte general
  app/Employee.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
  resources/views/vacation/report_general.blade.php
Labels: bug, enhancement, change

#597 fechas de retorno
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
Labels: bug

#596 reporte general
  app/Http/Controllers/Api/V1/DepartureController.php
  resources/views/vacation/note.blade.php
  resources/views/vacation/report_general.blade.php
  resources/views/vacation/report_individual.blade.php
Labels: bug, enhancement

#604 Adición de la columna de bono antiguedad en la planilla de haberes #603
  app/Employee.php
  app/EmployeePayroll.php
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/PayrollPrintController.php
  app/TotalPayrollEmployee.php
  resources/views/payroll/print.blade.php
Labels: change

#605 Quitar la opción de Vacaciones de la lista de solicitud de permisos
  resources/assets/js/components/departure/DepartureEdit.vue
Labels: bug, change

#606 Listado de todos los permisos, incluyendo vacaciones
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/EmployeeController.php
  routes/api.php
Labels: bug, change

#607 Modificación de la redacción de la nota de solicitud de días a cuenta…
  resources/views/vacation/note.blade.php
Labels: change

#612 Modificación de campo code
  resources/views/departure/transfers.blade.php
Labels: bug
