Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVA, pull requests merged in 2023-08, with the labels that each got.

#529 rango de vacaciones y bono de antiguedad segun CAS
  app/Http/Controllers/Api/V1/SeniorityBonusController.php
  app/Http/Controllers/Api/V1/VacationController.php
  app/Vacation.php
  resources/assets/js/components/vacation/SeniorityIndex.vue
  resources/assets/js/components/vacation/VacationIndex.vue
  resources/assets/js/menu.json
  resources/assets/js/routes.js
  routes/api.php
Labels: enhancement

#536 Adecuacion de Modelos y CRUD's
  app/CasCertification.php
  app/DaysOnVacation.php
  app/Departure.php
  app/Http/Controllers/Api/V1/DaysOnVacationController.php
  app/Http/Controllers/Api/V1/VacationController.php
  app/MinimumSalary.php
  app/VacationQueue.php
Labels: enhancement

#537 #526 migraciones de las tablas a implementar
  app/Departure.php
  app/DepartureReason.php
  app/Http/Controllers/Api/V1/DepartureController.php
  database/migrations/2023_07_31_161613_create_vacation_queues_table.php
  database/migrations/2023_07_31_183825_create_cas_certifications_table.php
  database/migrations/2023_08_14_154529_primary_key_departures_table.php
  database/migrations/2023_08_14_154946_create_days_on_vacations_table.php
  database/seeds/DepartureReasonVacationSeeder.php
Labels: enhancement

#539 Adición del campo code para la impresión de permisos
  resources/views/departure/print.blade.php
Labels: enhancement

#540 registro de permiso de vacacion v1
  app/Http/Controllers/Api/V1/DepartureController.php
  routes/api.php
Labels: enhancement

#541 Contador de días disponible para vacaciones
  app/Http/Controllers/Api/V1/CasCertificationController.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
  routes/api.php
Labels: enhancement

#543 eliminacion del permiso por vacacion
  app/Http/Controllers/Api/V1/DepartureController.php
  routes/api.php
Labels: enhancement

#545 Contador de días disponible para vacaciones por empleado
  app/Http/Controllers/Api/V1/VacationQueueController.php
  routes/api.php
Labels: enhancement

#549 Reportes y nota de solicitud de vacaciones PVA
  resources/assets/css/report-vacation-print.css
  resources/views/vacation/note.blade.php
  resources/views/vacation/report_general.blade.php
  resources/views/vacation/report_individual.blade.php
Labels: enhancement

#550 Nota de solicitud de permiso por vacaciones
  app/Employee.php
  app/Http/Controllers/Api/V1/DepartureController.php
  resources/views/vacation/note.blade.php
  routes/api.php
Labels: enhancement

#551 validacion en los metodos
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
Labels: enhancement

#553 dias de vacacion
  app/DaysOnVacation.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
Labels: enhancement

#552 Nota de solicitud de vacaciones
  app/DaysOnVacation.php
  resources/views/vacation/note.blade.php
Labels: enhancement

#554 Reportes de vacaciones general e individual
  app/Http/Controllers/Api/V1/DepartureController.php
  resources/views/vacation/report_general.blade.php
  resources/views/vacation/report_individual.blade.php
  routes/api.php
Labels: enhancement

#555 listado de dias de permiso
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/VacationQueueController.php
Labels: enhancement

#558 correción de error y métodos para impresión de reportes
  app/Departure.php
  app/Http/Controllers/Api/V1/DepartureController.php
  app/Http/Controllers/Api/V1/PositionGroupController.php
  resources/views/vacation/note.blade.php
  resources/views/vacation/report_individual.blade.php
  routes/api.php
Labels: bug, enhancement

#561 Development
  app/Console/Kernel.php
  docs/docker/README.md
  routes/api.php
Labels: enhancement

#564 bug count_days
  app/Http/Controllers/Api/V1/VacationQueueController.php
Labels: bug

#563 Interfaz de solicitud de vacaciones, implementado
  resources/assets/js/app.js
  resources/assets/js/components/departure/DepartureIndex.vue
  resources/assets/js/components/departure/VacationRequest.vue
Labels: enhancement

#565 Agregando mensajes de error, limpiado de variables
  resources/assets/js/components/departure/DepartureIndex.vue
  resources/assets/js/components/departure/VacationRequest.vue
Labels: enhancement

#568 Limpiando variables que no se usan y agregando restricciones de fecha…
  resources/assets/js/components/departure/VacationRequest.vue
Labels: enhancement

#569 Cambio de colores a los alerts
  resources/assets/js/app.js
  resources/assets/js/components/departure/VacationRequest.vue
Labels: change

#570 Agregando lógica para asignación de medias jornadas en dos permisos
  resources/assets/js/components/departure/VacationRequest.vue
Labels: enhancement

#571 Propuesta del formato de nota para la solicitud de vacaciones
  app/Http/Controllers/Api/V1/DepartureController.php
  resources/views/vacation/note.blade.php
Labels: enhancement, change

#574 Convirtiendo en mayúscula el texto del cite
  resources/assets/js/components/departure/VacationRequest.vue
Labels: enhancement

#577 soft delete y listado de permisos de vacacion
  app/Departure.php
  app/Http/Controllers/Api/V1/DepartureController.php
  database/migrations/2023_08_29_154529_drop_unique_cite_departures_table.php
  database/migrations/2023_08_29_154529_soft_delete_departures_table.php
Labels: enhancement

#581 bug eliminacion de permiso
  app/Console/Kernel.php
  app/Http/Controllers/Api/V1/DepartureController.php
Labels: bug

#582 Reporte de permisos por vacaciones
  app/DepartureReason.php
  app/Http/Controllers/Api/V1/DepartureController.php
  resources/views/vacation/report.blade.php
  routes/api.php
Labels: enhancement

#583 Refactorización del reporte de permisos por vacaciones
  app/Http/Controllers/Api/V1/DepartureController.php
  routes/api.php
Labels: bug

#586 Refactorización reporte general de vacaciones
  app/Http/Controllers/Api/V1/DepartureController.php
Labels: bug

#588 Corrección del reporte general de vacaciones
  app/Http/Controllers/Api/V1/DepartureController.php
Labels: bug

#589 Cambiando de icono a la solicitud de vacaciones
  resources/assets/js/components/departure/VacationRequest.vue
Labels: change

#590 Quitando botón de solicitud de salida, en la sección de vacaciones
  resources/assets/js/components/departure/VacationList.vue
Labels: bug

#591 Condiciones de parámetros en reporte
  resources/views/vacation/report_general.blade.php
  resources/views/vacation/report_individual.blade.php
Labels: bug
